config/routes.rb
Rails.application.routes.draw do
  resources :disbursement_transaction_logs
  resources :disbursement_transactions do
    member do
      post :disburse
    end
  end
  resources :disbursement_requests do
    member do
      post :approve
      post :reject
    end
  end
  get 'employee_deposit/index'

  # resources :employees
  root :to => "employees#index"


  resources :employees do
    get 'deposits', on: :collection
  end

  get 'startup/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :disbursement_requests, dependent: :destroy
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.order(created_at: :desc)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    default_employee_deposit_param = {:employee_deposit => employee_params[:salary]}
    @employee = Employee.new(employee_params.merge(default_employee_deposit_param))

    respond_to do |format|
      if @employee.save
        # format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        flash[:success] = "New employee has been created"
        format.html { redirect_to action: "index", notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :npwp, :no_ktp, :disburse_credit, :status, :level, :salary, :join_date, :bank_account_name, :bank_account_number, :bank_name, :phone_number, :email)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :employee_name %>
  </div>

  <div class="field">
    <%= form.label :npwp %>
    <%= form.text_area :npwp, id: :employee_npwp %>
  </div>

  <div class="field">
    <%= form.label :no_ktp %>
    <%= form.text_area :no_ktp, id: :employee_no_ktp %>
  </div>

  <div class="field">
    <%= form.label :disburse_credit %>
    <%= form.text_area :disburse_credit, id: :employee_disburse_credit %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_area :status, id: :employee_status %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_area :level, id: :employee_level %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary, id: :employee_salary %>
  </div>

  <div class="field">
    <%= form.label :join_date %>
    <%= form.text_field :join_date, id: :employee_join_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Npwp:</strong>
  <%= @employee.npwp %>
</p>

<p>
  <strong>No ktp:</strong>
  <%= @employee.no_ktp %>
</p>

<p>
  <strong>Disburse credit:</strong>
  <%= @employee.disburse_credit %>
</p>

<p>
  <strong>Status:</strong>
  <%= @employee.status %>
</p>

<p>
  <strong>Level:</strong>
  <%= @employee.level %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<p>
  <strong>Join date:</strong>
  <%= @employee.join_date %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>