config/routes.rb
Rails.application.routes.draw do
  resources :disbursement_transaction_logs
  resources :disbursement_transactions do
    member do
      post :disburse
    end
  end
  resources :disbursement_requests do
    member do
      post :approve
      post :reject
    end
  end
  get 'employee_deposit/index'

  # resources :employees
  root :to => "employees#index"


  resources :employees do
    get 'deposits', on: :collection
  end

  get 'startup/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/disbursement_transactions_controller.rb
class DisbursementTransactionsController < ApplicationController
  before_action :set_disbursement_transaction, only: [:show, :edit, :update, :destroy]

  # GET /disbursement_transactions
  # GET /disbursement_transactions.json
  def index
    @disbursement_transactions = DisbursementTransaction.where(status: "PENDING")
    @disbursement_transactions = @disbursement_transactions.sort_by &:created_at

  end

  # GET /disbursement_transactions/1
  # GET /disbursement_transactions/1.json
  def show
  end

  # GET /disbursement_transactions/new
  def new
    @disbursement_transaction = DisbursementTransaction.new
  end

  # GET /disbursement_transactions/1/edit
  def edit
  end

  def disburse
    disbursement_transaction = DisbursementTransaction.find(params[:id])
    disbursement_transaction.status = "Disbursed" 
    disbursement_transaction.save
    disbursement_transaction_log = DisbursementTransactionLog.new
    disbursement_transaction_log.disbursement_transaction_id = params[:id]
    disbursement_transaction_log.status = "SUCCESS"
    disbursement_transaction_log.save
    respond_to do |format|
      flash[:success] = "Amount of partially salary has been disbursed"
      format.html { redirect_to action: "index", notice: 'Disbursement transaction was successfully created.' }
    end
  end

  # POST /disbursement_transactions
  # POST /disbursement_transactions.json
  def create
    @disbursement_transaction = DisbursementTransaction.new(disbursement_transaction_params)

    respond_to do |format|
      if @disbursement_transaction.save
        format.html { redirect_to @disbursement_transaction, notice: 'Disbursement transaction was successfully created.' }
        format.json { render :show, status: :created, location: @disbursement_transaction }
      else
        format.html { render :new }
        format.json { render json: @disbursement_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disbursement_transactions/1
  # PATCH/PUT /disbursement_transactions/1.json
  def update
    respond_to do |format|
      if @disbursement_transaction.update(disbursement_transaction_params)
        format.html { redirect_to @disbursement_transaction, notice: 'Disbursement transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @disbursement_transaction }
      else
        format.html { render :edit }
        format.json { render json: @disbursement_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disbursement_transactions/1
  # DELETE /disbursement_transactions/1.json
  def destroy
    @disbursement_transaction.destroy
    respond_to do |format|
      format.html { redirect_to disbursement_transactions_url, notice: 'Disbursement transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disbursement_transaction
      @disbursement_transaction = DisbursementTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disbursement_transaction_params
      params.fetch(:disbursement_transaction, {})
    end
end

app/helpers/disbursement_transactions_helper.rb
module DisbursementTransactionsHelper
end

app/views/disbursement_transactions/_form.html.erb
<%= form_with(model: disbursement_transaction, local: true) do |form| %>
  <% if disbursement_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disbursement_transaction.errors.count, "error") %> prohibited this disbursement_transaction from being saved:</h2>

      <ul>
      <% disbursement_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disbursement_transactions/edit.html.erb
<h1>Editing Disbursement Transaction</h1>

<%= render 'form', disbursement_transaction: @disbursement_transaction %>

<%= link_to 'Show', @disbursement_transaction %> |
<%= link_to 'Back', disbursement_transactions_path %>

app/views/disbursement_transactions/new.html.erb
<h1>New Disbursement Transaction</h1>

<%= render 'form', disbursement_transaction: @disbursement_transaction %>

<%= link_to 'Back', disbursement_transactions_path %>

app/views/disbursement_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_disbursement_transaction_path(@disbursement_transaction) %> |
<%= link_to 'Back', disbursement_transactions_path %>